### ISSUE TITLE
Error : /bin/sh: 1: truffle: not found

### ISSUE THREAD

**Issue by vinhyenvodoi98** [sc-forks/solidity-coverage#382]
I I just installed and used this package in few days ago . it was great . but when I try to run it on Circle CI it gets this error.
```
./node_modules/.bin/solidity-coverage
Generating coverage environment
Running: truffle compile --network coverage 
(this can take a few seconds)...
/bin/sh: 1: truffle: not found
ls: no such file or directory: ./coverageEnv/build/contracts/*.json
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Instrumenting  ./coverageEnv/contracts/SimpleContract.sol
Running: truffle compile --network coverage 
(this can take a few seconds)...
/bin/sh: 1: truffle: not found
ls: no such file or directory: ./coverageEnv/build/contracts/*.json
Launched testrpc on port 8555
Running: truffle test --network coverage 
(this can take a few seconds)...
/bin/sh: 1: truffle: not found
Cleaning up...
Shutting down testrpc-sc (pid 1243)
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
Exited with code 1
```
This is my .circleci/config.yml
```
version: 2
jobs:
  build:
    working_directory: ~/smart-contracts
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:8-browsers
      # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      - image: trufflesuite/ganache-cli
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - run:
          name: Migrate Contracts
          command: ./node_modules/truffle/build/cli.bundled.js migrate --network development
      - run:
          name: Test Contracts
          command: ./node_modules/truffle/build/cli.bundled.js test --network development
      - run:
          name: Test coverage
          command: ./node_modules/.bin/solidity-coverage
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
```

this is my repo : https://github.com/vinhyenvodoi98/Test_Contract_With_Truffle/tree/CircleCI
thanks for this great package :+1:
