### ISSUE TITLE
Stange behavior when running inside a github workflow

### ISSUE THREAD

**Issue by migoldfinger** [sc-forks/solidity-coverage#794]
Well, I do not know if this is really a problem of solidity-coverage or solidity or even github.
Steps to reproduce
1) Create a new hardhat typescript project and put it in a github repository.
2) Setup a workflow that runs the tests with code coverage and access the coverage folder afterwards
------------------------
I did run into that problem when I wanted to setup a workflow to automatically host the created html pages in the converage folder.

Strange things happened:

a) In my tests the workflow fails every time after setup when running normal

b) every rerun of the workflow will fail to with the same behavior

c) When rerun the workflow with debug log enabled the workflow will succeed

d) After succeeding once the workflow seems to succeed every time now (at least the 4-5 times I restarted the workflow for testing)

------------------------

The logs from successful runs and failed runs differ in an important part
This is the part from  my workflow file 
```
jobs:
  # Generate docs from inline documentation
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          check-latest: false
      - name: Prepare npm
        run: npm i
      - name: Generate test coverage report
        run: npm run test:coverage # "npm run build && cross-env NODE_OPTIONS=\"--max-old-space-size=2048\" hardhat coverage"
      - name: Generate docs from inline documentation
        run: npm run doc # Generates inline documentation and copies the coverage folder to the docs folder
      - name: Upload Build Artifact - Documentation
        uses: actions/upload-artifact@v3
        with:
          name: 'docs'
          path: './docs'
          if-no-files-found: error
          retention-days: 1
```
If the build failes name: Generate test coverage report show  as last log entries
```
...
Compilation:
============

Downloading compiler 0.8.18
```
The next task name: Generate docs from inline documentation fails with "Error: ENOENT: no such file or directory" when looking for the coverage folder
If the build succeed name: Generate test coverage report show  as last log entries
```
------------|----------|----------|----------|----------|----------------|
File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------|----------|----------|----------|----------|----------------|
 contracts/ |      100 |      100 |      100 |      100 |                |
  Lock.sol  |      100 |      100 |      100 |      100 |                |
------------|----------|----------|----------|----------|----------------|
All files   |      100 |      100 |      100 |      100 |                |
------------|----------|----------|----------|----------|----------------|

> Istanbul reports written to ./coverage/ and ./coverage.json
```
which sounds logical since now the folder is created.

I see 2 options
O1) The hardhat coverage process just returns without an error and without creating the coverage folder. I suspect in this case some error has happened I just do not see it
O2) the github workflow starts the "name: Generate docs from inline documentation" task before the other task is finished. Personally I think that is not even possible but who knows.

Ether way I have no Idea how to address this problem.
Additional plugins I had loaded
"hardhat-contract-sizer" # Shows contract sizes after build so maybe an other hind since this is affecting the build process...
"hardhat-abi-exporter"
"solidity-ast"
"solidity-docgen"
